# Setup
title:               লেখালেখি
tagline:             সৈয়দ আবদাল আহমদ | সাংবাদিক ও কলামিস্ট
url:                 https://www.syedabdalahmed.com
enforce_ssl:         www.syedabdalahmed.com
paginate:            6
paginate_path:       "/lekhalekhi/page:num/"
baseurl:             "/"
permalink:           /lekhalekhi/:title

# About/contact
author:
  name:              Syed Abdal Ahmed
  email:             abdal62@gmail.com


# Gems
gems:
  - jekyll-paginate
